version: '3.8'

services:

  postgres:
    image: bitnami/postgresql:latest
    restart: always
    container_name: db-nlw-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql_db

volumes:
  postgres_data:
